export interface Food {
  description: string;
  id: number;
  image: string;
  ingredients: string[];
  name: string;
  price: number;
  spicy: boolean;
  vegetarian: boolean;
}

export const allProducts: Food[] = [
  {
    description: "",
    id: 0,
    image: "https://i.imgur.com/8B8YLOo.jpg",
    ingredients: ["tomato sauce", "mozzarella"],
    name: "Margherita",
    price: 17,
    spicy: false,
    vegetarian: true,
  },
  {
    description: "",
    id: 1,
    image: "https://i.imgur.com/OHHctnf.jpg",
    ingredients: ["tomato sauce", "mozzarella", "double pepperoni"],
    name: "Pepperoni",
    price: 20,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 2,
    image: "https://i.imgur.com/3ZTwCfz.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "ham",
      "mushrooms",
      "beef cubes",
    ],
    name: "Rome",
    price: 25.75,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 3,
    image: "https://i.imgur.com/dyoOLCO.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "pepperoni",
      "tomatoes",
      "green pepper",
      "red onion",
      "jalapenos",
      "Samourai sauce",
    ],
    name: "American Spicy",
    price: 30.25,
    spicy: true,
    vegetarian: false,
  },
  {
    description: "",
    id: 4,
    image: "https://i.imgur.com/wOEuXuV.jpg",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "ham",
      "pepperoni",
      "mushrooms",
      "green pepper",
    ],
    name: "Quattro Stagioni",
    price: 27.25,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 5,
    image: "https://i.imgur.com/48Zw4K3.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "feta cheese",
      "ham",
      "pork cubes",
      "red onion",
    ],
    name: "Pork & Feta",
    price: 27.25,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 6,
    image: "https://i.imgur.com/MDrTvkI.jpg",
    ingredients: [
      "mozzarella",
      "cheddar cheese",
      "emmentaler",
      "blue cheese",
      "oregano",
    ],
    name: "Quattro Formaggi",
    price: 35.15,
    spicy: false,
    vegetarian: true,
  },
  {
    description: "",
    id: 7,
    image: "https://i.imgur.com/0vPtSSO.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "chicken breast",
      "beef cubes",
      "pepperoni",
      "bacon",
    ],
    name: "Carnivora",
    price: 27.25,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 8,
    image: "https://i.imgur.com/lZtwJgy.png",
    ingredients: [
      "marinated chicken",
      "TABASCO spicy sauce",
      "red pepper sauce",
      "blue cheese",
      "green pepper",
      "red onion",
    ],
    name: "Louisiana Chicken",
    price: 20,
    spicy: true,
    vegetarian: false,
  },
  {
    description: "",
    id: 9,
    image: "https://i.imgur.com/SoZu61g.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "marinated chicken in Honey Mustard sauce",
      "cheddar cheese",
      "red onion",
    ],
    name: "Honey Mustard Chicken",
    price: 19.8,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 10,
    image: "https://i.imgur.com/mqTgvgl.png",
    ingredients: [
      "mozzarella",
      "sweet chilli sauce",
      "pepperoni",
      "pineapple",
      "jalapenos",
      "red onion",
    ],
    name: "Hawaiian",
    price: 27.25,
    spicy: true,
    vegetarian: false,
  },
  {
    description: "",
    id: 11,
    image: "https://i.imgur.com/k6IGrUd.png",
    ingredients: ["tomato sauce", "mozzarella", "ham", "mushrooms", "olives"],
    name: "Classic",
    price: 27.25,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 12,
    image: "https://i.imgur.com/yOe5RtC.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "pastrami",
      "salty cheese",
      "baked green pepper",
      "red onion",
    ],
    name: "Pastrami",
    price: 27.25,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 13,
    image: "https://i.imgur.com/ipMA5LP.png",
    ingredients: [
      "Honey Mustard sauce",
      "mozzarella",
      "pastrami",
      "sausages",
      "chilli pepper",
      "red onion",
    ],
    name: "Hot Pastrami",
    price: 27.25,
    spicy: true,
    vegetarian: false,
  },
  {
    description: "",
    id: 14,
    image: "https://i.imgur.com/E67Xf8Y.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "bacon",
      "corn",
      "onion",
      "mushrooms",
    ],
    name: "Country",
    price: 27.25,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 15,
    image: "https://i.imgur.com/v4sa2cA.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "cheddar cheese",
      "salty cheese",
      "tomatoes",
      "chilli pepper",
      "oregano",
    ],
    name: "Hot Cheese",
    price: 27.25,
    spicy: true,
    vegetarian: true,
  },
  {
    description: "",
    id: 16,
    image: "https://i.imgur.com/w5IQ2rX.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "tuna",
      "corn",
      "onion",
      "olives",
    ],
    name: "Ocean",
    price: 30,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 17,
    image: "https://i.imgur.com/znqS9KD.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "BBQ sauce",
      "onion",
      "corn",
      "bacon",
      "mushrooms",
      "sausages",
    ],
    name: "BBQ",
    price: 28.5,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 18,
    image: "https://i.imgur.com/cYpO8RT.png",
    ingredients: [
      "tomato sauce",
      "mozzarella",
      "salsa sauce",
      "pepperoni",
      "corn",
      "onion",
      "jalapenos",
      "tortilla chips",
    ],
    name: "Mexicana",
    price: 28.5,
    spicy: true,
    vegetarian: false,
  },
  {
    description: "",
    id: 0,
    image: "https://i.imgur.com/IXDJ52k.png",
    ingredients: ["penne", "ragu sauce", "beef cubes", "mozzarella"],
    name: "Bolognese",
    price: 28,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 1,
    image: "https://i.imgur.com/3jKSuUu.png",
    ingredients: ["penne", "white cream and garlic sauce", "bacon", "parmesan"],
    name: "Carbonara",
    price: 28,
    spicy: false,
    vegetarian: true,
  },
  {
    description: "",
    id: 0,
    image: "https://i.imgur.com/QWXH2NC.png",
    ingredients: [
      "chicken breast",
      "bacon",
      "parmesan",
      "cherry tomatoes",
      "croutons",
      "lettuce",
      "beetroot",
      "sauce of your choice",
    ],
    name: "Caesar",
    price: 20,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 1,
    image: "https://i.imgur.com/qChqf83.png",
    ingredients: [
      "feta cheese",
      "green olives",
      "cherry tomatoes",
      "cucumbers",
      "red onion",
      "red pepper",
      "oregano",
      "lettuce",
      "beetroot",
      "sauce of your choice",
    ],
    name: "Greek",
    price: 20,
    spicy: false,
    vegetarian: true,
  },
  {
    description: "",
    id: 2,
    image: "https://i.imgur.com/Ph0IjrX.png",
    ingredients: [
      "tuna",
      "green olives",
      "corn",
      "red pepper",
      "red onion",
      "lettuce",
      "beetroot",
      "sauce of your choice",
    ],
    name: "Tuna",
    price: 20,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "A delicious cake with chocolate and hazelnuts",
    id: 0,
    image: "https://i.imgur.com/7WbfaDN.png",
    ingredients: [],
    name: "Brownie",
    price: 15,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "Tortilla filled with chocolate cream",
    id: 1,
    image: "https://i.imgur.com/Mgsc3IZ.png",
    ingredients: [],
    name: "Chocolate Tortilla",
    price: 12,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "Hot pie with apple and cinnamon",
    id: 2,
    image: "https://i.imgur.com/OWIVhWX.png",
    ingredients: [],
    name: "Apple Pie",
    price: 15,
    spicy: false,
    vegetarian: true,
  },
  {
    description: "Cheesecake with berries topping",
    id: 3,
    image: "https://i.imgur.com/AsldA7x.png",
    ingredients: [],
    name: "Cheesecake",
    price: 15,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "Coca Cola 330ml",
    id: 0,
    image: "https://i.imgur.com/nJ6LeWv.png",
    ingredients: [],
    name: "Coca Cola",
    price: 5,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "Fanta 330ml",
    id: 1,
    image: "https://i.imgur.com/1WDkfme.png",
    ingredients: [],
    name: "Fanta",
    price: 5,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "Sprite 330ml",
    id: 2,
    image: "https://i.imgur.com/qP4Nx1x.jpg",
    ingredients: [],
    name: "Sprite",
    price: 5,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "Dorna 0.5L",
    id: 3,
    image: "https://i.imgur.com/yYuuaL1.jpg",
    ingredients: [],
    name: "Water",
    price: 4.5,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "Dorna 0.5L",
    id: 4,
    image: "https://i.imgur.com/0nyJk19.jpg",
    ingredients: [],
    name: "Sparkling water",
    price: 4.5,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "Fuzetea 0.5L Peach or Lemon",
    id: 5,
    image: "https://i.imgur.com/dsHumXE.jpg",
    ingredients: [],
    name: "Fuzetea",
    price: 5,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 0,
    image: "https://i.imgur.com/k5Dg7hZ.png",
    ingredients: [],
    name: "BBQ",
    price: 4,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 1,
    image: "https://i.imgur.com/k5Dg7hZ.png",
    ingredients: [],
    name: "Pizza",
    price: 4,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 2,
    image: "https://i.imgur.com/k5Dg7hZ.png",
    ingredients: [],
    name: "Salsa",
    price: 4,
    spicy: true,
    vegetarian: false,
  },
  {
    description: "",
    id: 3,
    image: "https://i.imgur.com/k5Dg7hZ.png",
    ingredients: [],
    name: "Sweet Chilli",
    price: 4,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 4,
    image: "https://i.imgur.com/k5Dg7hZ.png",
    ingredients: [],
    name: "Spicy TABASCO",
    price: 4,
    spicy: true,
    vegetarian: false,
  },
  {
    description: "",
    id: 5,
    image: "https://i.imgur.com/OmejA2J.png",
    ingredients: [],
    name: "Mayonnaise",
    price: 4,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 6,
    image: "https://i.imgur.com/k5Dg7hZ.png",
    ingredients: [],
    name: "Ketchup",
    price: 4,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "",
    id: 7,
    image: "https://i.imgur.com/OmejA2J.png",
    ingredients: [],
    name: "Garlic sauce",
    price: 4,
    spicy: false,
    vegetarian: false,
  },
  {
    description: "Baked potatoes, slightly spicy",
    id: 0,
    image: "https://i.imgur.com/sxP6sJt.png",
    ingredients: [],
    name: "Wedges",
    price: 6,
    spicy: false,
    vegetarian: true,
  },
  {
    description: "Fried onion rings",
    id: 1,
    image: "https://i.imgur.com/i3Jintb.png",
    ingredients: [],
    name: "Onion rings",
    price: 6,
    spicy: false,
    vegetarian: true,
  },
  {
    description: "Cabbage salad, carrots and dressing",
    id: 2,
    image: "https://i.imgur.com/HNX30U9.png",
    ingredients: [],
    name: "Coleslaw",
    price: 10,
    spicy: false,
    vegetarian: false,
  },
];
